set-option -g default-shell /bin/zsh

# TERMINAL / COLORS
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# GENERAL
set -g mouse on

# Change prefix from Ctrl-b to Ctrl-a
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Start windows and panes at 1 instead of 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# COPY MODE
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'niksingh710/minimal-tmux-status'

# minimal-tmux-status
set -g @minimal-tmux-justify "left"

# Keep this at the very bottom
run '~/.tmux/plugins/tpm/tpm'
